Tagging thumbnail image
farhan-helmy/ratemysurau pull request #69
Opened 2023-07-24 15:48 UTC by ismi-abbas

- This include some issue #42 - Only implemented dropzone uploader
- Remove image after upload - remove from server
- New preview image ui

2023-07-24 17:00 UTC, Xavier-IV reviewed
Hey, great work! Not sure if my input will be valuable or external review allowed.

Added some small comments. Feel free to take a look!

2023-07-24 23:42 UTC, ismi-abbas commented on src/components/shared/CustomToast.tsx
> +        icon={({ type }) =>
Hey thanks for the review. Definitely would have to separate it. I'll make a change

2023-07-24 23:43 UTC, ismi-abbas commented on src/components/shared/CustomUpload.tsx
> +const capitalizeStart = (str: string) => {
Good idea. I put here at first because it's just duplication of sample dropzone from uploadthing with some customization.

2023-07-24 23:45 UTC, ismi-abbas commented
I haven't update the yarn-lock on this since I'm using pnpm on local(i just notice that). So it should need to pull latest package and updated yarn-lock on staging.

2023-07-25 02:26 UTC, farhan-helmy commented on src/components/shared/CustomUpload.tsx
> +const capitalizeStart = (str: string) => {
kami amat perlu review dari senior dev seperti kamu, hahahah @Xavier-IV

2023-07-25 02:26 UTC, farhan-helmy commented
dah ready ke PR ni? kalau ada changes lagi boleh convert to draft

2023-07-25 02:36 UTC, ismi-abbas commented on src/components/shared/CustomUpload.tsx
> +const capitalizeStart = (str: string) => {
ok utils yang sama dah exist rupanya 😂, reuse je.

2023-07-25 02:59 UTC, farhan-helmy requested changes

2023-07-25 02:59 UTC, farhan-helmy commented on src/components/AddSurauForm.tsx
> +    await deleteSurau.mutateAsync(id).then(() => console.log("Done"));
```suggestion
    await deleteSurau.mutateAsync(id);

```

2023-07-25 03:04 UTC, farhan-helmy approved these changes

2023-07-25 03:05 UTC, farhan-helmy commented
dont forget to update yarn.lock, sebab nampak ada version change dalam package.json

2023-07-25 03:32 UTC, ismi-abbas commented
> dont forget to update yarn.lock, sebab nampak ada version change dalam package.json

<img width="520" alt="image" src="https://github.com/farhan-helmy/ratemysurau/assets/77921975/704f5c18-c0d6-4603-b765-6eccfd522b72">

Risau..  Kalau kau update from main directly? Aku rasa branch ni dah lama tak align yarn-lock.

2023-07-25 03:35 UTC, farhan-helmy commented
> > dont forget to update yarn.lock, sebab nampak ada version change dalam package.json
> 
> <img alt="image" width="520" src="https://user-images.githubusercontent.com/77921975/255780495-704f5c18-c0d6-4603-b765-6eccfd522b72.png">
> Risau.. Kalau kau update from main directly? Aku rasa branch ni dah lama tak align yarn-lock.

ok takpe biar dulu

2023-07-25 03:36 UTC, merged

2023-07-25 09:03 UTC, Xavier-IV commented
Great work! Thanks for the PR 🚀